language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
#  - hhvm

# faster builds on new travis setup not using sudo
sudo: false

# cache vendor dirs
cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - travis_retry composer update --dev --prefer-dist --no-interaction
  # install php extensions
  - |
    if (php --version | grep -i HipHop > /dev/null); then
      echo "Skipping imagick and gmagick tests on HHVM"
    else
      pear config-set preferred_state beta
      printf "\n" | pecl install imagick
      # gmagick is not installed on travis currently
      #printf "\n" | pecl install gmagick
    fi
# setup application:
  - |
    ./init --env=Development
    sed -i s/root/travis/ common/config/main-local.php
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" frontend/config/main.php
    sed -i "s/'cookieValidationKey' => ''/'cookieValidationKey' => 'testkey'/" backend/config/main.php

before_script:
  - mysql -e 'CREATE DATABASE yii2advanced_test;'
  - php yii_test migrate --interactive=0

script:
  - composer validate --strict
  - vendor/bin/codecept run
